Neos:
  Neos:
    fusion:
      autoInclude:
        Garagist.Fontawesome: true
  Fusion:
    defaultContext:
      Garagist.Fontawesome: Garagist\Fontawesome\EelHelper\IconHelper
  Flow:
    mvc:
      routes:
        Garagist.Fontawesome:
          position: 'before Neos.Neos'
